stages:

  get-data:
  
    cmd: python src/get_data.py
      --output_folder ${data.output_folder}

    deps:
      - src/get_data.py

    params:
      - data

    outs:
      - ${data.output_folder}

    metrics:
      - ${data.metrics_file}:
          cache: false

  fit:
    cmd: 
      python src/fit.py
      ${data.output_folder}
      ${fit.output_folder}
      ${fit.metrics_folder}
    deps:
    - ${data.output_folder}
    - src/fit.py
    params:
      - fit
    outs:
    - ${fit.output_folder}
    metrics:
      - ${fit.metrics_folder}.json:
          cache: false
    plots:
      - ${fit.metrics_folder}:
          cache: false
