data:
  data_date: 2022/08/08

  output_folder: outs/data
  metrics_file: outs/data_metrics.json

fit:
  output_folder: outs/fit
  metrics_folder: outs/fit_metrics
  metrics_file: outs/fit_metrics.json

  epochs: 8

